### ISSUE TITLE
Dell DW1560 Wireless

### ISSUE THREAD

**Issue by hazelement** [linusyang92/macOS-ThinkPad-T480s#1]
Hi I'm new to hackintosh and I have a T480. You mentioned you swapped the wifi card with Dell DW1560 Wireless. But I looked on ebay for this card and a lot of seller are saying this card is not compatible with lenovo laptops. What am I missing here? Thanks.

**Comment by linusyang92** [comment]
@hazelement Older Lenovo/HP laptops have **a BIOS whitelist** which forbids users installing Wi-Fi cards of other brands (like Dell). The latest generation of Thinkpad laptops such as T480/T480s/X1 Carbon Gen 6 do not have such whitelist any more, so we can install any Wi-Fi cards. DW1560 is confirmed to be compatible with T480s.
