### ISSUE TITLE
updating to catalina beta results in kernel panic

### ISSUE THREAD

**Issue by rtotheb2000** [linusyang92/macOS-ThinkPad-T480s#23]
Hi, first of all, this repository is very much appreciated. However, I found that I am unable to update to Catalina. I have posted my problems on https://www.tonymacx86.com/threads/t480s-having-problems-updating.280904/post-1984389 but so far no solution ... 

update: a combination of two approaches (including yours) led to success. Not sure what caused the updating issue in the first place starting from 10.14.6 beta (which I installed using your clover folder without hiccups). Judging from my current approach it is one of the kexts in kexts/Other.

update 2: I found VirtualSMC.kext to cause the kernel panic.

**Comment by kekkokk** [comment]
can you provide some steps? that might be useful

**Comment by rtotheb2000** [comment]
I am not sure what steps you want to see. I provide the EFI used to install Catalina beta at this repository now https://github.com/rtotheb2000/macOS-ThinkPad-T480s-catalina. Maybe this helps you? At this point, there are a lot of things not working. I can not change the properties of the touchpad, Bluetooth is not working atm, I have issues with sudden reboots when I use the USB-C connector to drive an external display and there are probably much more. So it is definitely working progress.
