### ISSUE TITLE
Wrong processor shown in "about this mac"

### ISSUE THREAD

**Issue by vistree** [linusyang92/macOS-ThinkPad-T480s#4]
First of all: absolutly great repro!!! I used it and were able to install a most working system. Thank you!!
I have one question: I recognised, that looking at "About this Mac" I see a wrong CPU. I get: 1,8 GHz Intel Core i5 - but my machine has an 1,6 GHz Intel Core i5
Where is the 1,8 coming from? Is this something you have overridden? Must I be worried about the difference - so is Mac OS really "thinking" I have a faster CPU then I really have?

**Comment by linusyang92** [comment]
@vistree This is caused by Apple and not a real issue. Everyone's i5 8250u shows "1.8 GHz":

https://www.tonymacx86.com/threads/success-macos-10-14-on-thinkpad-t480s.261318/
https://www.tonymacx86.com/threads/solved-dell-inspiron-7472-i5-8250u-coffee-lake-sierra.235443/

**Comment by vistree** [comment]
@linusyang92 - thanx for clarifying!
