### ISSUE TITLE
DSL-file for Voodoo releated SSDT-KBD.aml

### ISSUE THREAD

**Issue by vistree** [linusyang92/macOS-ThinkPad-T480s#7]
Hi @linusyang92 , I have a problem with using the voodoo-driver for keyboard and trackpad. Boot loops until I enable verbose mode in boot options. Any idea? Can you provide the SSDT-KBD.dsl you used to create the ACPI-aml file to be used with the voodoo-kext? Or, any idea why my machine loops?

**Comment by linusyang92** [comment]
@vistree I upload the `dsl` source file in the same directory. Check it out. The boot loop should not be cause by this `aml` file but maybe by some other incompatible drivers.

**Comment by vistree** [comment]
Thanx for offereing the voodooPS2 related dsl file - I will check it out ;-)
