### ISSUE TITLE
Which version of ApplePS2SmartTouchPad.kext is used?

### ISSUE THREAD

**Issue by vistree** [linusyang92/macOS-ThinkPad-T480s#8]
Hi @linusyang , which version of ApplePS2SmartTouchPad.kext is used in your repro? Is it already the latest SmartTouchpad v4.7 beta 5? Do you know if there is any chance to make the Trackpoint and the 3 click-keys work?

**Comment by vistree** [comment]
Sorry, just recognised on the repro readme: Keyboard/Elan Touchpad (PS/2) using ApplePS2SmartTouchPad.kext v4.7b5 by EMlyDinEsH 
So, just the questions regarding Trackpoint are valid ;-)

**Comment by linusyang92** [comment]
@vistree 
> Do you know if there is any chance to make the Trackpoint and the 3 click-keys work?

First of all, the stock ApplePS2SmartTouchPad driver does not even work on T480/T480s. I read the kernel logs and reverse-engineer the driver to make it properly detect the trackpad device.

Making it support Trackpoint is not my priority. I personally only use the trackpad. You can try yourself to disassemble the driver and patch it.

Notice that trackpad/trackpoint on T480s (maybe also T480) are manufactured by ELAN and connected to the PS/2 ports but not I2C ports. So, the only existing multi-touch driver for the device is the closed source one. I personally do not like this driver, but there is no second choice.

**Comment by vistree** [comment]
Thanx for clarification!!!
